version: "3.6"
services:

    postgres:
      image: postgres:11.1-alpine
      container_name: skeleton-challenge-mark-0-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234567
        - POSTGRES_DB=skeleton_challenge_mark_0
      ports:
        - "5435:5432"
      env_file:
        - .env

    #mysql:
    #  image: mysql:5.7
    #  container_name: skeleton-challenge-mark-0-mysql
    #  working_dir: /application
    #  volumes:
    #    - .:/application
    #  environment:
    #    - MYSQL_ROOT_PASSWORD=mdalycodb
    #    - MYSQL_DATABASE=lliege_challenge
    #    - MYSQL_USER=cristiane
    #    - MYSQL_PASSWORD=mdalycodb
    #  ports:
    #    - "3308:3306"

    php-fpm:
      build: docker/php-fpm
      container_name: skeleton-challenge-mark-0-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      env_file:
        - .env

    webserver:
      image: nginx:alpine
      container_name: skeleton-challenge-mark-0-webserver
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8000:80"
      depends_on:
        - postgres
        - php-fpm
      env_file:
        - .env
