version: "3.6"
services:

    mysql:
      image: mysql:5.7
      container_name: lliege-challenge-api-mysql
      env_file:
        - .env.dev.local
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=mdalycodb
        - MYSQL_DATABASE=lliege_challenge
        - MYSQL_USER=cristiane
        - MYSQL_PASSWORD=mdalycodb
      ports:
        - "3308:3306"

    webserver:
      image: nginx:alpine
      container_name: lliege-challenge-api-webserver
      env_file:
        - .env.dev.local
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"
      depends_on:
        - mysql

    php-fpm:
      build: docker/php-fpm
      container_name: lliege-challenge-api-php-fpm
      env_file:
        - .env.dev.local
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
